'use strict';
const $=id=>document.getElementById(id), canvas=$('map'), ctx=canvas.getContext('2d');
let data, t=0, playing=true, selected=null, scale=1, cx=0,cy=0,w=1,h=1,drag=null,moved=false,previous=0,current=[],fitScale=1,flowStats=new Map();
const mph=v=>v*2.236936;
function screen(x,y){return [(x-cx)*scale+w/2,h/2-(y-cy)*scale]}
function world(x,y){return [(x-w/2)/scale+cx,(h/2-y)/scale+cy]}
function fit(){const pts=data.lanes.flatMap(l=>l.shape),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys);cx=(a+b)/2;cy=(c+d)/2;scale=Math.min((w-110)/(b-a),(h-110)/(d-c));fitScale=scale;$('follow').checked=false}
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function states(){const frames=data.frames;let lo=0,hi=frames.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(frames[mid].time<=t)lo=mid;else hi=mid-1}const a=frames[lo],b=frames[Math.min(lo+1,frames.length-1)],f=b.time===a.time?0:(t-a.time)/(b.time-a.time);const next=new Map(b.vehicles.map(v=>[v[0],v]));return a.vehicles.map(v=>{const n=next.get(v[0]);if(!n)return v;const p=v.slice();p[1]=v[1]+(n[1]-v[1])*f;p[2]=v[2]+(n[2]-v[2])*f;return p})}
function endTime(){return data.frames[data.frames.length-1].time}
function clockText(){if(data.meta.replay_start_local){const parts=data.meta.replay_start_local.slice(11).split(':').map(Number),secs=parts[0]*3600+parts[1]*60+parts[2]+Math.floor(t);return [Math.floor(secs/3600),Math.floor(secs/60)%60,secs%60].map(n=>String(n).padStart(2,'0')).join(':')}return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function inspect(v){if(!selected){$('details').textContent='No vehicle selected.';return}if(!v){$('details').textContent=selected+' is not present at this time. Scrub back or pick another car.';return}const fields=[['Speed',mph(v[3]).toFixed(1)+' mph'],['Acceleration',v[7].toFixed(2)+' m/s²'],['Lane',v[5]],['Lane position',v[6].toFixed(1)+' m'],['Nearby traffic',FlowLayer.peerText(v,flowStats)],['Model','Krauss'],['Vehicle length','5.0 m']];$('details').replaceChildren();const id=document.createElement('div');id.className='carid';id.textContent=v[0];$('details').append(id);const dl=document.createElement('dl');for(const [k,val]of fields){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=val;dl.append(dt,dd)}$('details').append(dl)}
function draw(){ctx.clearRect(0,0,w,h);current=states();flowStats=FlowLayer.aggregate(current);const v=current.find(v=>v[0]===selected);if(v&&$('follow').checked){cx=v[1];cy=v[2]}ctx.strokeStyle='#172b37';ctx.lineWidth=1;const spacing=500;let [left,top]=world(0,0),[right,bottom]=world(w,h);for(let x=Math.floor(left/spacing)*spacing;x<right;x+=spacing){const [sx]=screen(x,0);ctx.beginPath();ctx.moveTo(sx,0);ctx.lineTo(sx,h);ctx.stroke()}for(let y=Math.floor(bottom/spacing)*spacing;y<top;y+=spacing){const [,sy]=screen(0,y);ctx.beginPath();ctx.moveTo(0,sy);ctx.lineTo(w,sy);ctx.stroke()}
for(const road of data.context_roads||[]){ctx.beginPath();road.shape.forEach((p,i)=>{const q=screen(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.lineWidth=Math.max(1,5*scale);ctx.strokeStyle='#243a47';ctx.stroke()}
FlowLayer.drawRoads(ctx,data.lanes,screen,scale,flowStats,$('road-flow')?.checked);
// Road labels come from the source network; suppress duplicates.
ctx.font='11px system-ui';ctx.fillStyle='#7895a4';const names=new Set();for(const lane of [...data.lanes,...(data.context_roads||[]).filter(r=>(data.context_labels||[]).includes(r.name))]){if(!lane.name||names.has(lane.name))continue;names.add(lane.name);const p=lane.shape[Math.floor(lane.shape.length/2)],q=screen(...p);if(q[0]>0&&q[0]<w-80&&q[1]>70&&q[1]<h-70){ctx.fillText(lane.name,q[0]+10,q[1]-15)}else{names.delete(lane.name)}}
drawDetectorMarkers();drawRampMarkers();
for(const car of current){let [x,y]=screen(car[1],car[2]);if(x< -20||x>w+20||y< -20||y>h+20)continue;ctx.save();ctx.translate(x,y);ctx.rotate(car[4]*Math.PI/180);ctx.fillStyle=FlowLayer.carColor(car,flowStats,$('car-colors')?.value);ctx.fillRect(-Math.max(1.4,1*scale),-Math.max(2.4,2.5*scale),Math.max(2.8,2*scale),Math.max(4.8,5*scale));ctx.restore();if(car[0]===selected){ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,Math.max(8,5*scale),0,Math.PI*2);ctx.stroke()}}
if($('zoom-level'))$('zoom-level').textContent=(scale/fitScale).toFixed(1)+'×';$('count').textContent=current.length;$('mean').textContent=current.length?mph(current.reduce((a,v)=>a+v[3],0)/current.length).toFixed(1):'—';$('clock').textContent=clockText();$('timeline').value=t;inspect(v);if(data.comparison)updateComparison()}
function tick(now){if(data){if(playing&&previous){t=Math.min(endTime(),t+Math.min((now-previous)/1000,.15)*Number($('rate').value));if(t>=endTime()){playing=false;$('play').textContent='Play'}}draw()}previous=now;requestAnimationFrame(tick)}
$('play').onclick=()=>{if(t>=endTime())t=0;playing=!playing;$('play').textContent=playing?'Pause':'Play'};$('restart').onclick=()=>{t=0;selected=null};$('timeline').oninput=e=>{t=Number(e.target.value);playing=false;$('play').textContent='Play'};$('fit').onclick=()=>data&&fit();$('zoom').onclick=()=>zoomAt(1.5,w/2,h/2);if($('zoom-out'))$('zoom-out').onclick=()=>zoomAt(1/1.5,w/2,h/2);$('pick').onclick=()=>{if(current.length)selected=current[Math.floor(current.length/2)][0]};
function zoomAt(factor,x,y){if(!data)return;const before=world(x,y);scale=Math.max(fitScale*.3,Math.min(25,scale*factor));const after=world(x,y);cx+=before[0]-after[0];cy+=before[1]-after[1];$('follow').checked=false}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});
canvas.ondblclick=e=>{const r=canvas.getBoundingClientRect();zoomAt(2,e.clientX-r.left,e.clientY-r.top)};
const pointers=new Map();let pinch=null,gesture=false;
canvas.onpointerdown=e=>{canvas.focus({preventScroll:true});pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);if(pointers.size===1){drag=[e.clientX,e.clientY,cx,cy];moved=false;gesture=false}if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a[0]-b[0],a[1]-b[1]),center:[(a[0]+b[0])/2,(a[1]+b[1])/2]};gesture=true;drag=null}};
canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2&&pinch){const [a,b]=[...pointers.values()],center=[(a[0]+b[0])/2,(a[1]+b[1])/2],distance=Math.hypot(a[0]-b[0],a[1]-b[1]),r=canvas.getBoundingClientRect();if(pinch.distance>0)zoomAt(distance/pinch.distance,pinch.center[0]-r.left,pinch.center[1]-r.top);cx-=(center[0]-pinch.center[0])/scale;cy+=(center[1]-pinch.center[1])/scale;pinch={distance,center};return}if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.hypot(dx,dy)>4)moved=true;if(moved){cx=drag[2]-dx/scale;cy=drag[3]+dy/scale;$('follow').checked=false}};
canvas.onpointerup=e=>{if(!moved&&!gesture&&data){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let distance=18,best=null;for(const v of current){const q=screen(v[1],v[2]),d=Math.hypot(x-q[0],y-q[1]);if(d<distance){distance=d;best=v[0]}}selected=best}pointers.delete(e.pointerId);pinch=null;drag=null;if(pointers.size===1){const a=[...pointers.values()][0];drag=[...a,cx,cy];moved=true}};
canvas.onpointercancel=e=>{pointers.delete(e.pointerId);pinch=null;drag=null;gesture=true};
canvas.onkeydown=e=>{if(!data)return;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();$('follow').checked=false;if(e.key==='0')fit();else if(e.key==='+'||e.key==='=')zoomAt(1.5,w/2,h/2);else if(e.key==='-')zoomAt(1/1.5,w/2,h/2);else{cx+=({'ArrowLeft':-100,'ArrowRight':100}[e.key]||0)/scale;cy+=({'ArrowUp':100,'ArrowDown':-100}[e.key]||0)/scale}}};
window.addEventListener('resize',resize);resize();requestAnimationFrame(tick);
async function loadReplay(){const embedded=$('embedded-replay');if(embedded)return JSON.parse(embedded.textContent);const path=document.body.dataset.replay||'replay.json.gz';let r=await fetch(path);if(!r.ok&&path==='replay.json.gz')r=await fetch('replay.json');if(!r.ok)throw Error('Replay unavailable');const d=await (path.endsWith('.gz')&&r.url.endsWith('.gz')?new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json():r.json());if(d.chunks){const parts=await Promise.all(d.chunks.map(async path=>{const response=await fetch(path);if(!response.ok)throw Error('Replay segment unavailable');return new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).json()}));d.frames=parts.flat();delete d.chunks}return d}
loadReplay().then(d=>{data=d;setupFlowControls();$('networkname').textContent=d.meta.scenario;fit();$('timeline').max=endTime();$('play').disabled=false;$('play').textContent='Pause';$('provenance').textContent=JSON.stringify(d.meta,null,2);$('status').textContent=`SUMO replay · seed ${d.meta.seed} · ${d.meta.report.completed_trips} completed trips ${d.meta.drain_report?"by demand cutoff":"in full run"} · sampled every ${d.meta.sample_seconds||1} s; display interpolates positions`;if(d.comparison)setupComparison()}).catch(e=>{$('status').textContent=e.message+' — refresh or run locally';$('play').textContent='Error'});
let comparisonKey='';
function drawDetectorMarkers(){if(!data.comparison)return;ctx.font='11px system-ui';for(const s of data.comparison.input_markers){const q=screen(...s.network_xy);ctx.fillStyle='#e8c679';ctx.beginPath();ctx.arc(...q,5,0,Math.PI*2);ctx.fill();ctx.fillText(s.direction+' entry · '+s.id,q[0]+9,q[1]-7)}const s=data.comparison.stations.find(s=>s.id===$('compare-station')?.value);if(s){const q=screen(...s.network_xy);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(...q,8,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff';ctx.fillText('Compare · '+s.id,q[0]+10,q[1]+15)}}
function setupComparison(){const panel=$('comparison');if(!panel)return;panel.hidden=false;for(const s of data.comparison.stations){const o=document.createElement('option');o.value=s.id;o.textContent=s.id+' · '+s.direction+' · '+s.name;$('compare-station').append(o)}const preferred=data.comparison.stations.find(s=>data.comparison.records.some(r=>r.station_id===s.id&&r.eligible));if(preferred)$('compare-station').value=preferred.id;$('compare-station').onchange=()=>{comparisonKey='';updateComparison()};const m=data.comparison.metrics;$('diagnostics').textContent=`Same-day baseline across ${m.eligible_bins} fully observed downstream station-bins after warm-up: count MAE ${m.count.mae.toFixed(1)} vehicles / 5 min; count weighted absolute error ${m.count.wape_percent.toFixed(1)}%; speed MAE ${m.speed_mph.mae.toFixed(1)} mph. No driver-parameter calibration or held-out validation.`;$('run-report').textContent=`Full run starting ${data.meta.start_local.slice(11,16)}: ${data.meta.report.scheduled.toLocaleString()} scheduled, ${data.meta.report.inserted.toLocaleString()} inserted, ${data.meta.report.running} still travelling at cutoff; ${data.meta.report.waiting} waiting to enter; ${data.meta.report.collisions} collisions, ${data.meta.report.teleports} teleports. Visible playback starts ${data.meta.replay_start_local.slice(11,16)} and lasts ${endTime()/60} minutes.`;updateComparison()}
function updateComparison(){if(!$('comparison'))return;const sid=$('compare-station').value,bin=Math.floor((t+data.meta.replay_offset_seconds)/300)*300,key=sid+'/'+bin+'/'+w;if(key===comparisonKey)return;comparisonKey=key;const rows=data.comparison.records.filter(r=>r.station_id===sid),r=rows.find(r=>r.begin===bin);$('compare-values').replaceChildren();if(r){for(const [label,k,unit]of [['Speed','speed_mph','mph'],['Count','count','vehicles / 5 min']]){const p=document.createElement('p'),o=r.observed[k],s=r.simulated[k];p.textContent=`${label}: reported ${o===null?'missing':o.toFixed(1)} ${unit} · simulated ${s===null?'missing':s.toFixed(1)} ${unit}`;$('compare-values').append(p)}$('compare-quality').textContent=r.timestamp_local.slice(11,16)+' source-local interval start · '+r.percent_observed+'% observed · '+(r.eligible?'included in diagnostic score':'excluded from score: '+r.excluded_reasons.join(', '));}for(const [id,k]of [['compare-speed','speed_mph'],['compare-count','count']])drawComparisonChart(id,k,rows,bin)}
function drawComparisonChart(id,key,rows,bin){const c=$(id),x=c.getContext('2d'),cw=c.clientWidth,ch=180,ratio=devicePixelRatio||1;c.width=cw*ratio;c.height=ch*ratio;c.style.height=ch+'px';x.scale(ratio,ratio);const values=rows.flatMap(r=>[r.observed[key],r.simulated[key]]).filter(v=>v!==null),max=Math.max(1,...values)*1.1,end=rows[rows.length-1].end;const px=v=>45+v/end*(cw-65),py=v=>150-v/max*125;x.font='11px system-ui';x.fillStyle='#91aeba';for(let i=0;i<3;i++){const v=max*i/2;x.fillText(v.toFixed(0),3,py(v)+4);x.strokeStyle='#29404d';x.beginPath();x.moveTo(45,py(v));x.lineTo(cw-20,py(v));x.stroke()}for(const source of ['observed','simulated']){x.strokeStyle=source==='observed'?'#63dcc4':'#edb980';x.lineWidth=2;x.beginPath();let last=false;for(const r of rows){const v=r[source][key];if(v===null){last=false;continue}const q=[px(r.begin+150),py(v)];last?x.lineTo(...q):x.moveTo(...q);last=true}x.stroke();for(const r of rows){const v=r[source][key];if(v!==null){x.fillStyle=source==='observed'?'#63dcc4':'#edb980';x.beginPath();x.arc(px(r.begin+150),py(v),source==='observed'?3:2,0,Math.PI*2);x.fill()}}}x.fillStyle='#a4bdc9';for(const r of rows.filter((_,i)=>i%3===0))x.fillText(r.timestamp_local.slice(11,16),px(r.begin),175);x.fillStyle='#ffffff16';x.fillRect(px(bin),15,px(bin+300)-px(bin),135);x.fillStyle='#91aeba';x.fillText('Warm-up bins excluded from score',45,12)}

function drawRampMarkers(){if(!data.meta.ramp_plan)return;ctx.font='10px system-ui';for(const e of data.meta.ramp_plan.bindings){const q=screen(...e.network_xy);ctx.fillStyle=e.kind==='entry'?'#edb980':'#b89ee8';ctx.fillRect(q[0]-3,q[1]-3,6,6);if(scale>1.3)ctx.fillText(e.station+' '+(e.kind==='entry'?'ON':'OFF'),q[0]+7,q[1]+5)}}
if($('pick-ramp'))$('pick-ramp').onclick=()=>{const origins=new Set(data?.meta.ramp_plan?.bindings.filter(e=>e.kind==='entry').map(e=>'o'+e.station));const choices=current.filter(v=>origins.has(v[0].split('-')[0]));if(choices.length){selected=choices[Math.floor(Math.random()*choices.length)][0];$('follow').checked=true;scale=Math.max(scale,3)}else $('details').textContent='No ramp car present at this time.'};

function setupFlowControls(){const jump=$('jump');if(jump){const locations=[...(data.meta.ramp_plan?.bindings||[]).map(e=>({name:e.direction+' '+(e.kind==='entry'?'on-ramp':'exit')+' · '+e.station,xy:e.network_xy})),...(data.comparison?.stations||[]).map(s=>({name:s.direction+' '+s.name+' · '+s.id,xy:s.network_xy}))];for(const l of locations){const o=document.createElement('option');o.value=JSON.stringify(l.xy);o.textContent=l.name;jump.append(o)}jump.onchange=()=>{if(!jump.value)return;[cx,cy]=JSON.parse(jump.value);scale=Math.max(scale,2);$('follow').checked=false};if(!locations.length)jump.parentElement.hidden=true}const legend=()=>{if($('flow-legend'))$('flow-legend').innerHTML=FlowLayer.legend($('car-colors')?.value,$('road-flow')?.checked)};if($('car-colors'))$('car-colors').onchange=legend;if($('road-flow'))$('road-flow').onchange=legend;legend()}
