'use strict';
const $=id=>document.getElementById(id), canvas=$('map'), ctx=canvas.getContext('2d');
let data, t=0, playing=true, selected=null, scale=1, cx=0,cy=0,w=1,h=1,drag=null,moved=false,previous=0,current=[];
const mph=v=>v*2.236936, color=v=>v<8?'#ef9868':v<20?'#e7c874':'#63dcc4';
function screen(x,y){return [(x-cx)*scale+w/2,h/2-(y-cy)*scale]}
function world(x,y){return [(x-w/2)/scale+cx,(h/2-y)/scale+cy]}
function fit(){const pts=data.lanes.flatMap(l=>l.shape),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys);cx=(a+b)/2;cy=(c+d)/2;scale=Math.min((w-110)/(b-a),(h-110)/(d-c));$('follow').checked=false}
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function states(){let i=Math.min(Math.floor(t),data.frames.length-1),a=data.frames[i],b=data.frames[Math.min(i+1,data.frames.length-1)],f=t-i;const next=new Map(b.vehicles.map(v=>[v[0],v]));return a.vehicles.map(v=>{const n=next.get(v[0]);if(!n)return v;const p=v.slice();p[1]=v[1]+(n[1]-v[1])*f;p[2]=v[2]+(n[2]-v[2])*f;return p})}
function inspect(v){if(!selected){$('details').textContent='No vehicle selected.';return}if(!v){$('details').textContent=selected+' is not present at this time. Scrub back or pick another car.';return}const fields=[['Speed',mph(v[3]).toFixed(1)+' mph'],['Acceleration',v[7].toFixed(2)+' m/s²'],['Lane',v[5]],['Lane position',v[6].toFixed(1)+' m'],['Model','Krauss'],['Vehicle length','5.0 m']];$('details').replaceChildren();const id=document.createElement('div');id.className='carid';id.textContent=v[0];$('details').append(id);const dl=document.createElement('dl');for(const [k,val]of fields){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=val;dl.append(dt,dd)}$('details').append(dl)}
function draw(){ctx.clearRect(0,0,w,h);current=states();const v=current.find(v=>v[0]===selected);if(v&&$('follow').checked){cx=v[1];cy=v[2]}ctx.strokeStyle='#172b37';ctx.lineWidth=1;const spacing=500;let [left,top]=world(0,0),[right,bottom]=world(w,h);for(let x=Math.floor(left/spacing)*spacing;x<right;x+=spacing){const [sx]=screen(x,0);ctx.beginPath();ctx.moveTo(sx,0);ctx.lineTo(sx,h);ctx.stroke()}for(let y=Math.floor(bottom/spacing)*spacing;y<top;y+=spacing){const [,sy]=screen(0,y);ctx.beginPath();ctx.moveTo(0,sy);ctx.lineTo(w,sy);ctx.stroke()}
for(const road of data.context_roads||[]){ctx.beginPath();road.shape.forEach((p,i)=>{const q=screen(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.lineWidth=Math.max(1,5*scale);ctx.strokeStyle='#243a47';ctx.stroke()}
for(const lane of data.lanes){ctx.beginPath();lane.shape.forEach((p,i)=>{const q=screen(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.lineWidth=Math.max(1,lane.width*scale);ctx.strokeStyle='#405461';ctx.stroke()}
// Road labels come from the source network; suppress duplicates.
ctx.font='11px system-ui';ctx.fillStyle='#7895a4';const names=new Set();for(const lane of [...data.lanes,...(data.context_roads||[]).filter(r=>(data.context_labels||[]).includes(r.name))]){if(!lane.name||names.has(lane.name))continue;names.add(lane.name);const p=lane.shape[Math.floor(lane.shape.length/2)],q=screen(...p);if(q[0]>0&&q[0]<w-80&&q[1]>70&&q[1]<h-70){ctx.fillText(lane.name,q[0]+10,q[1]-15)}else{names.delete(lane.name)}}
for(const car of current){let [x,y]=screen(car[1],car[2]);if(x< -20||x>w+20||y< -20||y>h+20)continue;ctx.save();ctx.translate(x,y);ctx.rotate(car[4]*Math.PI/180);ctx.fillStyle=color(car[3]);ctx.fillRect(-Math.max(1.4,1*scale),-Math.max(2.4,2.5*scale),Math.max(2.8,2*scale),Math.max(4.8,5*scale));ctx.restore();if(car[0]===selected){ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,Math.max(8,5*scale),0,Math.PI*2);ctx.stroke()}}
$('count').textContent=current.length;$('mean').textContent=current.length?mph(current.reduce((a,v)=>a+v[3],0)/current.length).toFixed(1):'—';$('clock').textContent=Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');$('timeline').value=t;inspect(v)}
function tick(now){if(data){if(playing&&previous){t=Math.min(data.frames.length-1,t+Math.min((now-previous)/1000,.15)*Number($('rate').value));if(t>=data.frames.length-1){playing=false;$('play').textContent='Play'}}draw()}previous=now;requestAnimationFrame(tick)}
$('play').onclick=()=>{if(t>=data.frames.length-1)t=0;playing=!playing;$('play').textContent=playing?'Pause':'Play'};$('restart').onclick=()=>{t=0;selected=null};$('timeline').oninput=e=>{t=Number(e.target.value);playing=false;$('play').textContent='Play'};$('fit').onclick=()=>data&&fit();$('zoom').onclick=()=>scale=Math.min(25,scale*1.8);$('pick').onclick=()=>{if(current.length)selected=current[Math.floor(current.length/2)][0]};
canvas.onwheel=e=>{e.preventDefault();if(!data)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,before=world(x,y);scale=Math.max(.02,Math.min(25,scale*Math.exp(-e.deltaY*.001)));const after=world(x,y);cx+=before[0]-after[0];cy+=before[1]-after[1]};
canvas.addEventListener('wheel',e=>e.preventDefault(),{passive:false});
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,cx,cy];moved=false;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;let dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.hypot(dx,dy)>4)moved=true;if(moved){cx=drag[2]-dx/scale;cy=drag[3]+dy/scale;$('follow').checked=false}};canvas.onpointerup=e=>{if(!moved&&data){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let distance=18,best=null;for(const v of current){const q=screen(v[1],v[2]),d=Math.hypot(x-q[0],y-q[1]);if(d<distance){distance=d;best=v[0]}}selected=best}drag=null};canvas.onpointercancel=()=>drag=null;
window.addEventListener('resize',resize);resize();requestAnimationFrame(tick);
($('embedded-replay')?Promise.resolve(new Response($('embedded-replay').textContent)):fetch('replay.json.gz').then(async r=>{if(r.ok){if(typeof DecompressionStream==='undefined')throw Error('Use an up-to-date Chrome, Edge or Firefox browser');return new Response(r.body.pipeThrough(new DecompressionStream('gzip')))}return fetch('replay.json')})).then(r=>{if(!r.ok)throw Error('Replay unavailable');return r.json()}).then(d=>{data=d;$('networkname').textContent=d.meta.scenario;fit();$('timeline').max=d.frames.length-1;$('play').disabled=false;$('play').textContent='Pause';$('provenance').textContent=JSON.stringify(d.meta,null,2);$('status').textContent=`SUMO replay · seed ${d.meta.seed} · ${d.meta.report.completed_trips} completed trips · sampled every 1 s; positions interpolated between samples`}).catch(e=>{$('status').textContent=e.message+' — use python -m trafficlab demo';$('play').textContent='Error'});
