'use strict';
// Presentation only: controls select checked SUMO recordings, never browser physics.
(()=>{
 const $=id=>document.getElementById(id),canvas=$('road'),ctx=canvas.getContext('2d'),MPH=2.236936292;
 const PACE=[.9,1,1.1],HEADWAY=[1,1.5,2],cache=new Map();
 let index,geometry,reference,current,selectedCase,selectedRun,referenceRun,loaded=false,playing=false;
 let time=1810,lastTick=0,follow=true,driver=false,compare=false,selected=null,generation=0;
 let center=[0,0],scale=2.3,width=1,height=1,hitCars=[],lastEgo=null,drag=null,pointers=new Map(),pinch=null;
 const fmt=(v,n=1)=>Number(v).toFixed(n),signed=v=>(v>0?'+':'')+fmt(v),clock=t=>new Date((7.5*3600+t)*1000).toISOString().slice(11,19);
 const difference=v=>Math.abs(v)<.05?'No change':`${fmt(Math.abs(v))} s ${v<0?'quicker':'longer'}`;
 function table(node,headers,rows){const t=document.createElement('table'),tr=document.createElement('tr');for(const h of headers){const th=document.createElement('th');th.scope='col';th.textContent=h;tr.append(th)}t.append(tr);for(const row of rows){const r=document.createElement('tr');for(const cell of row){const td=document.createElement('td');td.textContent=cell;r.append(td)}t.append(r)}node.replaceChildren(t)}
 async function bundle(meta){
  if(cache.has(meta.file))return cache.get(meta.file);
  const promise=(async()=>{const response=await fetch('driver-data/'+meta.file);if(!response.ok)throw Error('A recording could not be downloaded.');const bytes=await response.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(hash!==meta.sha256)throw Error('Recording checksum mismatch. Playback stopped.');const json=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).json();if(json.frames){for(const f of json.frames){f.cars=f.cars.map(v=>[v[0],...v.slice(1,5),json.lane_ids[v[5]],v[6],0]);f.lookup=new Map(f.cars.map(v=>[v[0],v]))}}return json})();
  cache.set(meta.file,promise);promise.catch(()=>cache.delete(meta.file));if(cache.size>4)cache.delete(cache.keys().next().value);return promise;
 }
 function configuration(){return {tau:HEADWAY[+$('headway').value],speedFactor:PACE[+$('pace').value]}}
 function updateLabels(){const c=configuration();$('headway-value').textContent=fmt(c.tau)+' s';$('pace-value').textContent=Math.round(c.speedFactor*100)+'%';$('pace').setAttribute('aria-valuetext',`${Math.round(c.speedFactor*100)} percent of speed limit`);$('headway').setAttribute('aria-valuetext',`${c.tau} seconds desired headway`);for(const b of document.querySelectorAll('[data-preset]')){const match=b.dataset.preset==='easy'?c.tau===2&&c.speedFactor===.9:b.dataset.preset==='reference'?c.tau===1&&c.speedFactor===1:c.tau===1&&c.speedFactor===1.1;b.setAttribute('aria-pressed',match)}}
 function setPlaying(value){playing=value;$('play').textContent=playing?'Ⅱ Pause':'▶ Play'}
 async function choose(reset=false){
  const serial=++generation;updateLabels();loaded=false;setPlaying(false);$('play').disabled=true;compare=false;$('compare').setAttribute('aria-pressed','false');$('compare').textContent='Show reference traffic';
  $('load-status').textContent='Loading checked experiment…';$('scene-note').textContent='Loading the selected settings…';for(const id of ['target-change','cohort-change','changes'])$(id).textContent='—';$('moments').replaceChildren();draw();
  try{
   const c=configuration(),choice=index.cases.find(x=>x.tau===c.tau&&x.speedFactor===c.speedFactor);
   const replay=await bundle(choice.replay);if(serial!==generation)return;
   if(replay.key!==choice.key||replay.seed!==index.config.display_seed)throw Error('Recording identity mismatch.');
   current=replay;selectedCase=choice;selectedRun=choice.runs.find(r=>r.seed===42);selected=current.target;loaded=true;lastEgo=null;
   if(reset||time>selectedRun.target_arrival_s+10)time=selectedRun.target_depart_s+8;
   $('play').disabled=false;$('load-status').textContent='Experiment ready · inputs & integrity checked';showResults();setPlaying(!matchMedia('(prefers-reduced-motion: reduce)').matches);draw();
  }catch(e){if(serial!==generation)return;loaded=false;$('load-status').textContent=e.message;$('scene-note').textContent='Recording unavailable. Choose a setting to retry.';const retry=document.createElement('button');retry.textContent='Retry loading';retry.onclick=()=>choose(true);$('moments').append(retry);}
 }
 function showResults(){
  const r=selectedRun,b=referenceRun,d=r.difference;
  $('target-change').textContent=difference(d.target_trip);$('target-result').textContent=`${fmt(r.target_trip.mean_trip_s)} s vs ${fmt(b.target_trip.mean_trip_s)} s reference, including insertion delay.`;
  $('cohort-change').textContent=d.cohort===0?'No change':Math.abs(d.cohort)<.005?'<0.01 s / car':`${d.cohort>0?'+':''}${fmt(d.cohort,2)} s / car`;
  $('cohort-result').textContent=`Mean difference for the same ${r.cohort.n} other cars from this entry. Negative means quicker.`;
  $('changes').textContent=r.target_lane_changes.length;$('changes-result').textContent=`${b.target_lane_changes.length} in the reference. Changing lanes is not itself an aggression measure.`;
  const moments=$('moments');moments.replaceChildren();for(const event of r.target_lane_changes){const button=document.createElement('button'),t=+event.time;button.textContent=`${clock(t)} · lane change`;button.title=event.reason||'Recorded SUMO lane change';button.onclick=()=>{time=Math.max(index.config.replay_begin,t-5);follow=true;selected=current.target;compare=false;$('compare').setAttribute('aria-pressed','false');$('compare').textContent='Show reference traffic';setPlaying(true);draw()};moments.append(button)}
  if(!moments.children.length){const p=document.createElement('p');p.textContent='No lane changes in this trip. Try a different pace.';moments.append(p)}
  table($('diagnostics'),['Same-day discrepancy','Reference','Selected'],[['Count error · WAPE',fmt(b.diagnostics.count.wape_percent)+'%',fmt(r.diagnostics.count.wape_percent)+'%'],['Speed error · MAE',fmt(b.diagnostics.speed_mph.mae)+' mph',fmt(r.diagnostics.speed_mph.mae)+' mph']]);
  table($('seed-table'),['Seed','Your trip Δ','Group mean Δ','Opposite group Δ','All others Δ'],selectedCase.runs.map(x=>[x.seed,signed(x.difference.target_trip)+' s',fmt(x.difference.cohort,2)+' s',fmt(x.difference.opposite_direction,2)+' s',signed(x.difference.other_total_s)+' vehicle-s']));
  const values=selectedCase.runs.map(x=>x.difference.target_trip);$('seed-range').textContent=`Your paired trip difference ranges from ${signed(Math.min(...values))} to ${signed(Math.max(...values))} seconds across these three seeds.`;
  const checks=$('checks');checks.replaceChildren();for(const [text,ok]of [[`All ${r.accounting.scheduled.toLocaleString()} scheduled trips finish in each run`,true],['No reported collisions or teleports at any simulation step',true],['Identical departure schedules, routes and comparison membership',true],['Identical sampled traffic in the 31 s pre-entry window',true],['Same 18 eligible detector bins, every setting and seed',true],['Individual responses and counterfactual accuracy: unvalidated',false]]){const li=document.createElement('li');li.textContent=text;if(!ok)li.className='unverified';checks.append(li)}
  $('cohort-definition').textContent=`Target: ${index.config.selection_rule} Comparison group: ${index.config.cohort_rule} All-other-trip totals include both directions and the rest of the hour; they are model-wide differences, not a localized psychological response.`;
 }
 function sample(data,t){const frames=data.frames;let low=0,high=frames.length-1;while(low<high){const mid=Math.ceil((low+high)/2);if(frames[mid].t<=t)low=mid;else high=mid-1}const a=frames[low],b=frames[Math.min(low+1,frames.length-1)],u=Math.max(0,Math.min(1,(t-a.t)/(b.t-a.t||1)));return a.cars.map(v=>{const w=b.lookup.get(v[0]);if(!w)return v;const angle=v[4]+(((w[4]-v[4]+540)%360)-180)*u;return [v[0],v[1]+(w[1]-v[1])*u,v[2]+(w[2]-v[2])*u,v[3]+(w[3]-v[3])*u,angle,v[5],v[6],0]})}
 function seriesAt(data,t){const i=Math.floor(t-(data.series[0]?.t||0)),s=data.series[i];return s&&Math.abs(s.t-t)<1.01?s:null}
 const screen=(x,y)=>[(x-center[0])*scale+width/2,height/2-(y-center[1])*scale];
 function path(points){ctx.beginPath();points.forEach((p,i)=>{const q=screen(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)})}
 function fit(){if(!geometry)return;const points=geometry.lanes.flatMap(l=>l.shape),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);center=[(minX+maxX)/2,(minY+maxY)/2];scale=Math.min((width-70)/(maxX-minX),(height-120)/(maxY-minY));follow=false;driver=false;draw()}
 function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*d);canvas.height=Math.round(height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
 function drawCar(v,color,outline=false){const [x,y]=screen(v[1],v[2]);if(x< -25||x>width+25||y< -25||y>height+25)return;const length=Math.max(5,5*scale),wide=Math.max(2.5,1.8*scale);ctx.save();ctx.translate(x,y);ctx.rotate(v[4]*Math.PI/180);ctx.beginPath();ctx.roundRect(-wide/2,0,wide,length,Math.min(wide*.28,2));if(outline){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()}else{ctx.fillStyle=color;ctx.shadowColor='#06121dcc';ctx.shadowBlur=3;ctx.fill();ctx.shadowBlur=0;if(scale>.7){ctx.fillStyle='#173039';ctx.fillRect(-wide*.32,length*.2,wide*.64,length*.18);ctx.fillStyle='#bde4df66';ctx.fillRect(-wide*.28,length*.67,wide*.56,length*.12)}}ctx.restore()}
 function tag(v,label,color,dy=-30){const [x,y]=screen(v[1],v[2]);ctx.font='600 10px system-ui';ctx.textAlign='center';const w=ctx.measureText(label).width+14;ctx.fillStyle='#11232bef';ctx.beginPath();ctx.roundRect(x-w/2,y+dy,w,18,4);ctx.fill();ctx.fillStyle=color;ctx.fillText(label,x,y+dy+13)}
 function gapLine(a,b,label){if(!a||!b)return;const p=screen(a[1],a[2]),q=screen(b[1],b[2]);ctx.save();ctx.strokeStyle='#dcdfb6b0';ctx.lineWidth=1;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();ctx.setLineDash([]);ctx.font='10px system-ui';ctx.textAlign='center';const x=(p[0]+q[0])/2,y=(p[1]+q[1])/2,w=ctx.measureText(label).width+12;ctx.fillStyle='#10242df2';ctx.fillRect(x-w/2,y+9,w,17);ctx.fillStyle='#e7efcf';ctx.fillText(label,x,y+21);ctx.restore()}
 function draw(){
  if(!ctx||!width)return;ctx.fillStyle='#15282c';ctx.fillRect(0,0,width,height);if(!loaded||!geometry)return;
  const data=compare?reference:current,cars=sample(data,time),ego=cars.find(v=>v[0]===data.target),s=seriesAt(data,time),car=cars.find(v=>v[0]===selected)||ego;
  if(ego)lastEgo=ego;if(follow&&car)center=[car[1],car[2]];const stats=FlowLayer.aggregate(cars),follower=s?.follower?cars.find(v=>data.ids[v[0]]===s.follower.id):null;
  if(driver)DriverView.draw(ctx,geometry,cars,car||lastEgo,width,height,stats,'relative');else{
   for(const road of geometry.context_roads){path(road.shape);ctx.strokeStyle='#294047';ctx.lineWidth=Math.max(.7,3*scale);ctx.stroke()}
   for(const lane of geometry.lanes){path(lane.shape);ctx.strokeStyle='#0b1b22';ctx.lineWidth=Math.max(2,(lane.width+1)*scale);ctx.stroke()}
   FlowLayer.drawRoads(ctx,geometry.lanes,screen,scale,stats,true);
   if(scale>.7){for(const lane of geometry.lanes){path(lane.shape);ctx.strokeStyle='#def2d51d';ctx.lineWidth=.6;ctx.setLineDash([3*scale,8*scale]);ctx.stroke()}ctx.setLineDash([])}
   const labelled=new Set();ctx.font='11px system-ui';ctx.textAlign='left';for(const road of geometry.context_roads){if(!geometry.context_labels.includes(road.name)||labelled.has(road.name))continue;const p=screen(...road.shape[Math.floor(road.shape.length/2)]);if(p[0]>30&&p[0]<width-120&&p[1]>100&&p[1]<height-90){ctx.fillStyle='#a6c1ba';ctx.fillText(road.name,p[0],p[1]);labelled.add(road.name)}}
   for(const v of cars)drawCar(v,v[0]===data.target?'#ffcf7c':v[0]===follower?.[0]?'#a1eccb':FlowLayer.carColor(v,stats,'relative'));
   if($('ghost').checked&&!compare&&current.key!==index.reference_key){const ghost=sample(reference,time).find(v=>v[0]===reference.target);if(ghost){drawCar(ghost,'#b4a2e8',true);if(scale>.65)tag(ghost,'REFERENCE','#c6b7f0',18)}}
   if($('show-gaps').checked&&ego&&s){const leader=cars.find(v=>data.ids[v[0]]===s.leader);gapLine(ego,leader,s.gap_m==null?'':fmt(s.gap_m)+' m');if(follower)gapLine(follower,ego,fmt(s.follower.gap_m)+' m')}
   if(ego)tag(ego,compare?'REFERENCE':'YOUR CAR','#ffcf7c');if(car&&car[0]!==data.target)tag(car,'SELECTED','#dbeeee');
  }
  hitCars=cars;$('who').textContent=car?.[0]===data.target?(compare?'REFERENCE CAR':'YOUR CAR'):'SELECTED CAR';$('speed').textContent=car?fmt(car[3]*MPH,0):'—';const isTarget=car?.[0]===data.target;
  $('gap').textContent=isTarget&&s?.gap_m!=null?fmt(s.gap_m,0)+' m':'—';$('behind').textContent=isTarget&&s?.follower?fmt(s.follower.gap_m,0)+' m':'—';$('gap').title=isTarget&&s?.time_gap_s!=null?fmt(s.time_gap_s,2)+' s net time gap':'No usable target leader sample (200 m search)';$('behind').title=s?.follower?`${s.follower.id} · ${fmt(s.follower.speed*MPH)} mph`:'No reported follower (200 m search)';
  $('scene-note').textContent=compare?'Reference traffic · same clock, same departure schedule':!ego?(time<selectedRun.target_depart_s?'Your car has not entered yet.':'Your car has finished its trip. Restart to ride again.'):driver?'Schematic ride-along · recorded SUMO motion':follow?(car?.[0]===data.target?'Following your car · drag to explore, scroll or pinch to zoom':'Following the selected car · use Follow your car to return'):'Explore the corridor · click any car to inspect';
  $('view-label').textContent=compare?'REFERENCE · fixed 100% pace / 1.0 s':`${Math.round(selectedCase.speedFactor*100)}% pace · ${fmt(selectedCase.tau)} s preference`;
  $('clock').textContent=clock(time);$('timeline').value=time;$('follow').setAttribute('aria-pressed',follow);$('map-view').setAttribute('aria-pressed',!driver);$('driver-view').setAttribute('aria-pressed',driver);
 }
 function zoom(factor,px=width/2,py=height/2){if(driver)return;const old=scale;scale=Math.max(.12,Math.min(6,scale*factor));center[0]+=(px-width/2)*(1/old-1/scale);center[1]-=(py-height/2)*(1/old-1/scale);draw()}
 function tick(now){const elapsed=Math.min((now-lastTick)/1000,.1);lastTick=now;const advancing=playing&&loaded;if(advancing){time+=elapsed*+$('rate').value;if(time>=index.config.replay_end){time=index.config.replay_end;setPlaying(false)}}if(advancing)draw();requestAnimationFrame(tick)}
 $('pace').addEventListener('input',()=>choose());$('headway').addEventListener('input',()=>choose());for(const b of document.querySelectorAll('[data-preset]'))b.onclick=()=>{if(!index)return;const p=b.dataset.preset;$('pace').value=p==='easy'?0:p==='hurry'?2:1;$('headway').value=p==='easy'?2:0;follow=true;scale=2.3;choose(true)};
 $('play').onclick=()=>{if(time>=index.config.replay_end)time=selectedRun.target_depart_s+8;setPlaying(!playing)};$('restart').onclick=()=>{if(!loaded)return;time=selectedRun.target_depart_s+1;selected=current.target;follow=true;setPlaying(true);draw()};$('timeline').oninput=e=>{time=+e.target.value;setPlaying(false);draw()};
 $('fit').onclick=fit;$('follow').onclick=()=>{if(!loaded)return;const already=follow&&selected===current.target;selected=current.target;follow=!already;if(follow&&scale<.8)scale=2.3;draw()};$('map-view').onclick=()=>{driver=false;draw()};$('driver-view').onclick=()=>{driver=true;follow=true;selected=current?.target;draw()};$('zoom-in').onclick=()=>zoom(1.3);$('zoom-out').onclick=()=>zoom(1/1.3);$('ghost').onchange=draw;$('show-gaps').onchange=draw;
 $('compare').onclick=()=>{if(!loaded)return;compare=!compare;$('compare').setAttribute('aria-pressed',compare);$('compare').textContent=compare?'Back to experiment':'Show reference traffic';draw()};
 canvas.addEventListener('wheel',e=>{if(!loaded||driver)return;e.preventDefault();follow=false;const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});
 canvas.addEventListener('pointerdown',e=>{if(!loaded||driver)return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);drag={x:e.clientX,y:e.clientY,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);drag.moved=true}});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const previous=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]),r=canvas.getBoundingClientRect();follow=false;if(pinch)zoom(d/pinch,(a[0]+b[0])/2-r.left,(a[1]+b[1])/2-r.top);pinch=d;return}if(drag&&(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>3||drag.moved)){drag.moved=true;follow=false;center[0]-=(e.clientX-previous[0])/scale;center[1]+=(e.clientY-previous[1])/scale;draw()}});
 function release(e){if(drag&&!drag.moved&&pointers.size===1){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let distance=15,found=null;for(const v of hitCars){const p=screen(v[1],v[2]),d=Math.hypot(p[0]-x,p[1]-y);if(d<distance){distance=d;found=v[0]}}if(found!==null){selected=found;draw()}}pointers.delete(e.pointerId);pinch=null;if(!pointers.size)drag=null}
 canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=null;pinch=null});canvas.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();if(loaded)setPlaying(!playing)}else if(e.key==='+'||e.key==='=')zoom(1.3);else if(e.key==='-')zoom(1/1.3);else if(e.key==='Escape')fit()});
 new ResizeObserver(resize).observe(canvas);requestAnimationFrame(tick);
 (async()=>{try{const response=await fetch('driver-data/index.json');if(!response.ok)throw Error('Experiment index unavailable.');index=await response.json();if(index.schema!=='trafficlab.driver-library.v1'||!index.gates.matched_inputs||!index.gates.identical_predeparture||!index.gates.all_trips_complete||!index.gates.collision_free||!index.gates.same_diagnostic_mask)throw Error('Experiment checks are incomplete.');const c=index.cases.find(x=>x.key===index.reference_key);[geometry,reference]=await Promise.all([bundle(index.geometry),bundle(c.replay)]);referenceRun=c.runs.find(r=>r.seed===42);$('pace').disabled=false;$('headway').disabled=false;await choose(true)}catch(e){$('load-status').textContent=e.message+' Reload to retry.';$('scene-note').textContent='Unable to load checked recordings.'}})();
})();
