"""Export existing SUMO internal lane shapes for the schematic driver camera."""
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
networks = {}
for path in sorted((root / 'scenarios').glob('*/network.net.xml')):
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    lanes = []
    for edge in ET.parse(path).getroot().findall('edge'):
        if edge.get('function') != 'internal':
            continue
        for lane in edge.findall('lane'):
            lanes.append({'id': lane.get('id'), 'width': float(lane.get('width', '3.2')),
                          'shape': [[float(v) for v in point.split(',')[:2]]
                                    for point in lane.get('shape').split()]})
    networks[digest] = lanes
content = ('// Generated by scripts/export-driver-geometry.py from frozen SUMO networks.\n'
           '// Keys are SHA-256 hashes; only matching-network connectors are displayed.\n'
           'const DriverGeometry=' + json.dumps(networks, separators=(',', ':')) + ';\n')
for folder in ('viewer', 'docs'):
    (root / folder / 'driver-geometry.js').write_text(content)
print(f'Exported {sum(map(len, networks.values()))} internal lanes from {len(networks)} networks.')
